name = "Simple"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "A simple Hugo theme compatible with older versions"
homepage = ""
tags = ["blog", "simple", "clean"]
features = ["blog"]
min_version = "0.60.0"

[author]
  name = "Hugo User"
  homepage = ""
